version: "3.8"

services:
  postgres:
    image: postgres:18-bookworm
    container_name: edlearn-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: edlearn
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: edlearn_db
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - edlearn-network
    restart: unless-stopped

  # Dùng bản mặc định
  redis:
    image: redis:8
    container_name: edlearn-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - edlearn-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: edlearn-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - edlearn-network
    restart: unless-stopped

  # chromadb:
  #   image: chromadb/chroma:latest
  #   container_name: edlearn-chroma
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - chroma_data:/chroma/chroma
  #   networks:
  #     - edlearn-network
  #   restart: unless-stopped

  # # Ollama vẫn giữ nguyên vì image chính thức của họ đã tối ưu sẵn
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: edlearn-ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - edlearn-network
  #   restart: unless-stopped

networks:
  edlearn-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data:
  # chroma_data:
  # ollama_data:
