spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:edlearn_db}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
